server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myschool
    username: root
    password: wyx49214
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
mybatis-plus:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.wyx.springboot.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl